//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LengendOfUni.rc
//
#define IDC_BUTTON_LOAD                 3
#define IDD_LENGENDOFUNI_DIALOG         102
#define IDD_MAINDLG                     102
#define IDR_MAINFRAME                   128
#define IDB_FACE                        129
#define IDD_SOLARSYSTEM_MAP             130
#define IDD_ECONOMY_PANEL               132
#define IDD_ARMY_PANEL                  133
#define IDD_CULTURE_PANEL               134
#define IDD_HUMANRES_PANEL              135
#define IDD_ASTROSOCIOLOGY_PANEL        136
#define IDD_NUCLEAR_PANEL               137
#define IDD_SPACEFIGHT_PANEL            138
#define IDD_PROTON_PANEL                139
#define IDD_ASTROPHYSICS_PANEL          140
#define IDD_CULTURETEC_PANEL            141
#define IDD_ECONOMYTEC_PANEL            142
#define IDD_ASTROSOCIOLOGY_TECTREE_DLG  143
#define IDD_NUCLEAR_TECTREE_DLG         144
#define IDB_NONAME                      144
#define IDD_SPACEFIGHT_TECTREE_DLG      145
#define IDD_PROTON_TECTREE_DLG          146
#define IDD_ASTROPHYSICS_TECTREE_DLG    147
#define IDD_CULTURE_TECTREE_DLG         148
#define IDD_ECONOMY_TECTREE_DLG         149
#define IDD_SET_WORKER_CNT_DLG          150
#define IDD_CHOOSE_MAN                  151
#define IDD_PLANET_PANEL                152
#define IDD_BARBACK_DLG                 153
#define IDD_BATTLE_DLG                  154
#define IDD_SELECT_ARMY_DLG             155
#define IDD_STARSYSTEM_MAP              156
#define IDD_MSGBOX_DLG                  157
#define IDD_ALIGNMENT_DLG               158
#define IDD_LOGON_DLG                   159
#define IDD_ABOUT_DLG                   160
#define IDD_HISTORY_DLG                 161
#define IDD_TOOLTIP_DLG                 162
#define IDD_CHEAT_DLG                   163
#define IDD_RESULT_DLG                  164
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_BUTTON3                     1002
#define IDC_BUTTON4                     1003
#define IDC_BUTTON5                     1004
#define IDC_BUTTON13                    1005
#define IDC_LINE_TOP                    1005
#define IDC_BUTTON6                     1005
#define IDC_BUTTON14                    1006
#define IDC_FRAME_BOTTOM                1006
#define IDC_BUTTON15                    1007
#define IDC_SOLARSYS_LINK               1007
#define IDC_BUTTON16                    1008
#define IDC_5LIGHTYEAR_LINK             1008
#define IDC_BUTTON7                     1010
#define IDC_BTN_SPACEFIGHT              1011
#define IDC_BTN_PROTON                  1012
#define IDC_BTN_ASTROPHYSICS            1013
#define IDC_BTN_CULTURETEC              1014
#define IDC_BTN_ECONOMYTEC              1015
#define IDC_10KLIGHTYEAR_LINK           1016
#define IDC_GALAXY_LINK                 1017
#define IDC_BTN_ECONOMY                 1018
#define IDC_COMBO1                      1019
#define IDC_COMBO_BARBACK               1019
#define IDC_LIST1                       1020
#define IDC_BTN_ARMY                    1021
#define IDC_LIST2                       1021
#define IDC_BTN_CULTURE                 1022
#define IDC_COMBO2                      1022
#define IDC_BTN_HUMANRES                1023
#define IDC_BUTTON_SETTARGET            1024
#define IDC_BUTTON_MODNUM               1025
#define IDC_BTN_ASTROSOCIOLOGY          1026
#define IDC_BTN_NUCLEAR                 1027
#define IDC_RADIO1                      1028
#define IDC_RADIO2                      1029
#define IDC_STATIC_POPULATION           1029
#define IDC_RADIO3                      1030
#define IDC_STATIC_ECONOMY              1030
#define IDC_RADIO4                      1031
#define IDC_STATIC_ARMY                 1031
#define IDC_RADIO5                      1032
#define IDC_STATIC_CULTURE              1032
#define IDC_RADIO6                      1033
#define IDC_STATIC_RESOURCE             1033
#define IDC_RADIO7                      1034
#define IDC_STATIC_TREACHERY            1034
#define IDC_RADIO8                      1035
#define IDC_STATIC_LEADER               1035
#define IDC_RADIO9                      1036
#define IDC_STATIC_DIRECTION            1036
#define IDC_STATIC_ENEMYNAME            1036
#define IDC_RADIO10                     1037
#define IDC_STATIC_MINING               1037
#define IDC_STATIC_MP                   1037
#define IDC_RADIO11                     1038
#define IDC_STATIC_MANUFACTURE          1038
#define IDC_RADIO12                     1039
#define IDC_STATIC_FACE                 1039
#define IDC_RADIO13                     1040
#define IDC_BUTTON_CHGLEADER            1040
#define IDC_STATIC_ENEMYFACE            1040
#define IDC_RADIO14                     1041
#define IDC_STATIC_WORKER               1041
#define IDC_RADIO15                     1042
#define IDC_STATIC_NAME                 1042
#define IDC_RADIO16                     1043
#define IDC_STATIC_TEC                  1043
#define IDC_STATIC_TECNAME              1044
#define IDC_SLIDER1                     1046
#define IDC_EDIT_NUM                    1047
#define IDC_BUTTON_MODCOUNT             1048
#define IDC_STATIC_CIVI                 1049
#define IDC_STAR_RES                    1050
#define IDC_STAR_POP                    1051
#define IDC_STATIC_STAR                 1052
#define IDC_BUTTON_BARBACK              1053
#define IDC_BUTTON_STOPE                1054
#define IDC_BUTTON_FACTORY              1055
#define IDC_BUTTON_CITY                 1056
#define IDC_STATIC_BARBACK              1057
#define IDC_STATIC_STOPE                1058
#define IDC_STATIC_FACTORY              1059
#define IDC_STATIC_CITY                 1060
#define IDC_BUTTON_BARBACK_OPEN         1061
#define IDC_STATIC_BARBACKNAME          1061
#define IDC_STATIC_PROCESS              1062
#define IDC_BUTTON_ATTCK                1062
#define IDC_COMBO_WEAPON                1063
#define IDC_BUTTON_PRODUCE0             1064
#define IDC_BUTTON_PRODUCE1             1065
#define IDC_BUTTON_FRIEND               1065
#define IDC_BUTTON_PRODUCE2             1066
#define IDC_BUTTON_PRODUCE3             1066
#define IDC_BUTTON_BOMB                 1066
#define IDC_COMBO_WEAPON2               1067
#define IDC_BUTTON_SPY                  1067
#define IDC_STATIC_PROCESS2             1068
#define IDC_COMBO_WEAPON3               1069
#define IDC_STATIC_PROCESS3             1070
#define IDC_LIST_WEAPON                 1071
#define IDC_EDIT_INFO                   1074
#define IDC_BUTTON_GENSKILL             1075
#define IDC_COMBO_ARMY                  1076
#define IDC_BUTTON_ARMY_ATTACK          1077
#define IDC_BUTTON_WEAPON_ATTACK        1078
#define IDC_BUTTON_STARSYS1             1079
#define IDC_BUTTON_STARSYS2             1080
#define IDC_BUTTON_STARSYS3             1081
#define IDC_BUTTON_STARSYS4             1082
#define IDC_BUTTON_PLAN_FINISH          1083
#define IDC_STATIC_YEAR                 1084
#define IDC_STATIC_BOMECNT              1085
#define IDC_BUTTON_PLAN_HISTORY         1085
#define IDC_STATIC_ZHIZICNT             1086
#define IDC_BUTTON_PLAN_SAVE            1086
#define IDC_BUTTON_PRODUCEBOMB          1087
#define IDC_BUTTON_PRODUCEZHIZI         1088
#define IDC_STATIC_BOMB_PERCENT         1090
#define IDC_STATIC_ZHIZI_PERCENT        1091
#define IDC_BUTTON_ARMY_PRACTICE        1092
#define IDC_BUTTON_EDUCATION            1093
#define IDC_STATIC_SPEAKER              1094
#define IDC_STATIC_CONTENT              1095
#define IDC_PROGRESS_ASIGNMENT          1096
#define IDC_STATIC_INFO                 1097
#define IDC_STATIC_TIP                  1098
#define IDC_EDIT1                       1099
#define IDC_BUTTON_ABOUT                1100
#define IDC_STATIC_PLAYER               1101
#define IDC_STATIC_TITLE                1102
#define IDC_EDIT_HISTORY                1103
#define IDC_STATIC_PROPERTY             1104
#define IDC_STATIC_DEPARTMENT           1105
#define IDC_CHECK_MUSIC                 1106
#define IDC_STATIC_LINK1                1108
#define IDC_STATIC_LINK2                1109
#define IDC_STATIC_RESULT               1109
#define IDC_STATIC_LINK3                1110
#define IDC_STATIC_SCORE                1110
#define IDC_STATIC_LINK4                1111
#define IDC_STATIC_LINK5                1112
#define IDC_STATIC_LINK6                1113
#define IDC_STATIC_LINK7                1114

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
